# -*- coding: utf-8 -*-
"""Train_Edge_AI_MobileNetV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1...

# Farm "Edge AI" Verification Script
This script demonstrates how to:
1. Setup a "Maize vs Cassava" dataset (Downloads a sample if none exists).
2. Fine-tune MobileNetV2 (Transfer Learning) for mobile devices.
3. Convert the model to TFLite.
4. Add Metadata (Labels) so React Native can read it easily.

**Hardware**: Runtime -> Change runtime type -> T4 GPU (Recommended for speed).
"""

# 1. Install Dependencies
# We use tflite-support for adding metadata
# !pip install -q tflite-support
# NOTE: Run 'pip install tflite-support' in your terminal manually if not installed.

import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
import pathlib

# Imports for Metadata Writer (Moved to inside try/except block)
# from tflite_support.metadata_writers import image_classifier
# from tflite_support.metadata_writers import writer_utils


print(f"TensorFlow Version: {tf.__version__}")

# 2. Dataset Setup
# For this demo, we will download a sample dataset (Flowers). 
# IN PRODUCTION: Replace 'data_dir' with the path to your 'cassava' and 'maize' folders.
# e.g., /content/dataset/cassava, /content/dataset/maize

dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir_origin = tf.keras.utils.get_file('flower_photos', origin=dataset_url, untar=True)
data_dir = pathlib.Path(data_dir_origin)

print(f"Data directory: {data_dir}")

# We will pretend the flower classes are our crops for this demo
# Ideally, you uploaded a zip to Colab and unzipped it:
# !unzip crops.zip -d /content/crops
# data_dir = pathlib.Path('/content/crops')

# Parameters
BATCH_SIZE = 32
IMG_SIZE = (224, 224) # MobileNetV2 expects 224x224 (fixed)

# 3. Data Loading
train_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=IMG_SIZE,
  batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=IMG_SIZE,
  batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
print(f"Detected classes: {class_names}")

# 4. Performance Tuning
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# 5. Data Augmentation
data_augmentation = tf.keras.Sequential([
  tf.keras.layers.RandomFlip('horizontal'),
  tf.keras.layers.RandomRotation(0.2),
])

# 6. Build the Model (MobileNetV2)
preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input

# Create the base model from the pre-trained model MobileNet V2
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SIZE + (3,),
                                               include_top=False,
                                               weights='imagenet')

# Freeze the base model
base_model.trainable = False

# Add classification head
global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
prediction_layer = tf.keras.layers.Dense(len(class_names), activation='softmax')

inputs = tf.keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = preprocess_input(x)
x = base_model(x, training=False)
x = global_average_layer(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = prediction_layer(x)

model = tf.keras.Model(inputs, outputs)

# Compile
base_learning_rate = 0.0001
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=base_learning_rate),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])

model.summary()

# 7. Train
initial_epochs = 5
history = model.fit(train_ds,
                    epochs=initial_epochs,
                    validation_data=val_ds)

# 8. Fine Tuning (Optional)
base_model.trainable = True
fine_tune_at = 100
for layer in base_model.layers[:fine_tune_at]:
  layer.trainable = False

model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              optimizer = tf.keras.optimizers.RMSprop(learning_rate=base_learning_rate/10),
              metrics=['accuracy'])

fine_tune_epochs = 5
total_epochs =  initial_epochs + fine_tune_epochs

history_fine = model.fit(train_ds,
                         epochs=total_epochs,
                         initial_epoch=history.epoch[-1],
                         validation_data=val_ds)

# 9. Convert to TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

tflite_model_path = 'crop_verification.tflite'
with open(tflite_model_path, 'wb') as f:
  f.write(tflite_model)

print(f"Model converted: {tflite_model_path}")

# 10. Add Metadata (Optional but recommended)
# This creates a labels.txt inside the .tflite file
labels_file = 'labels.txt'
with open(labels_file, 'w') as f:
    for name in class_names:
        f.write(name + '\n')

try:
    print("Attempting to add metadata...")
    # Imports for Metadata Writer
    from tflite_support.metadata_writers import image_classifier
    from tflite_support.metadata_writers import writer_utils

    # Metadata Writer Setup
    # Normalization: MobileNetV2 uses [-1,1] => (pixel - 127.5) / 127.5
    writer = image_classifier.MetadataWriter.create_for_inference(
        writer_utils.load_file(tflite_model_path), 
        [127.5], [127.5], 
        [labels_file]
    )

    model_with_metadata = writer.populate()

    final_model_path = 'crop_verification_metadata.tflite'
    with open(final_model_path, 'wb') as f:
      f.write(model_with_metadata)
    
    print(f"SUCCESS! Metadata added. Model saved to: {final_model_path}")

except ImportError:
    print("WARNING: tflite-support not installed or incompatible. Skipping metadata injection.")
    print("Saving standard TFLite model as 'crop_verification_metadata.tflite' for compatibility.")
    
    # helper to copy
    import shutil
    final_model_path = 'crop_verification_metadata.tflite'
    shutil.copyfile(tflite_model_path, final_model_path)
    print(f"SUCCESS! (Without metadata) Model saved to: {final_model_path}")

except Exception as e:
    print(f"WARNING: Metadata injection failed: {e}")
    print("Saving standard TFLite model as 'crop_verification_metadata.tflite' for compatibility.")
    
    import shutil
    final_model_path = 'crop_verification_metadata.tflite'
    shutil.copyfile(tflite_model_path, final_model_path)
    print(f"SUCCESS! (Without metadata) Model saved to: {final_model_path}")

print(f"Run: from google.colab import files; files.download('{final_model_path}')")

